### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by thegecko** [thegecko/web-bluetooth-dfu#19]
@mjdietzx @beaufortfrancois 

I was thinking of pushing out a release to npm/bower.
Are there any features / bugfixes we want before this happens?

**Comment by mjdietzx** [comment]
Do you think I should make a PR fixing this issue first?

https://github.com/thegecko/web-bluetooth-dfu/issues/18

Just basically making gattserver a global variable. Thats all i can think of for now.

**Comment by jyasskin** [comment]
I'm really sorry to bring bad news, but I think we're going to have to blacklist the DFU service because even in v11 the default firmware doesn't support checking update signatures. The risk that people will get phished into malicious updates just seems too high.

https://github.com/WebBluetoothCG/registries/issues/7

**Comment by thegecko** [comment]
sux.

**Comment by jyasskin** [comment]
Very much, yes. :-(

**Comment by beaufortfrancois** [comment]
Please let's start/continue this conversation at https://github.com/WebBluetoothCG/registries/issues/7

**Comment by beaufortfrancois** [comment]
It has been applied to latest chromium build. See https://codereview.chromium.org/1866853002
@thegecko might want to update README.md for now. 

Don't worry though, we're still pursuing this with a potential signed DFU service ;)

**Comment by thegecko** [comment]
On hold ATM, @beaufortfrancois feel free to create a PR

**Comment by thegecko** [comment]
Published!
